# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://cloudforet-io.github.io'
title = 'Cloudforet API'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
    [mkarkup.goldmark]
        [markup.goldmark.extensions]
            table = true
            strikethrough = true
            tasklist = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1


# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content/en'
  weight = 1


[params]
  BookTheme = 'light'
  BookToC = true
  BookLogo = 'logo.png'
  BookSection = '/'
  BookRepo = 'https://github.com/cloudforet-io/api-doc'
  # Requires 'BookRepo' param.
  # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
  # Github uses 'commit', Bitbucket uses 'commits'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  enableHeader = true
